#
# _config.yml for ffi-media
#

exclude: [ "CNAME", "Gemfile*", "LICENSE.txt", "README.md", "tmp", "*.sh" ]
include: [".well-known"]
production_url: https://ghashboard.marcuse.info
source_url: https://github.com/fileformat/ghashboard

title : Ghashboard
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..3
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
