name: fork-is-current

on:
  schedule:
    - cron: '42 0 * * 1'
  push:
  pull_request:
  workflow_dispatch:

jobs:
  fork-is-current:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run fork-is-current.sh
        run: |
          bin/fork-is-current.sh
        env:
          GH_TOKEN: ${{ github.token }}